# Generated by Django 4.1.3 on 2023-01-16 02:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_amenities_alter_room_category_and_more'),
        ('experiences', '0003_alter_experience_category_alter_experience_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0002_alter_wishlists_experiences_alter_wishlists_rooms_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlists',
            new_name='Wishlist',
        ),
    ]
